<template>
  <q-page class="q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-subtitle1 text-weight-bold">Proveedores</div><div class="text-caption text-grey-7">Directorio de proveedores registrados</div></div><q-space/><q-btn dense flat icon="add_business" label="Nueva compra" no-caps to="/compras/nueva"/></div>
    <q-card flat bordered><q-card-section class="q-pa-sm"><q-input v-model="search" dense outlined clearable placeholder="Buscar proveedor, NIT o teléfono"><template #prepend><q-icon name="search"/></template></q-input></q-card-section>
      <q-table flat dense :rows="filtered" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20}">
        <template #body-cell-nombre="p"><q-td :props="p"><q-btn flat dense no-caps color="primary" :label="p.value" @click="selected=p.row;dialog=true"/></q-td></template>
        <template #body-cell-datos="p"><q-td :props="p"><div>{{p.row.telefono||'Sin teléfono'}}</div><div class="text-caption">{{p.row.direccion||'Sin dirección'}}</div></q-td></template>
        <template #body-cell-actions="p"><q-td :props="p"><q-btn-dropdown dense flat color="primary" icon="more_vert" dropdown-icon="none"><q-list dense style="min-width:150px"><q-item clickable v-close-popup @click="openEdit(p.row)"><q-item-section avatar><q-icon name="edit" color="primary"/></q-item-section><q-item-section>Modificar</q-item-section></q-item><q-separator/><q-item clickable v-close-popup class="text-negative" @click="removeProvider(p.row)"><q-item-section avatar><q-icon name="delete"/></q-item-section><q-item-section>Eliminar</q-item-section></q-item></q-list></q-btn-dropdown></q-td></template>
      </q-table>
    </q-card>
    <q-dialog v-model="dialog"><q-card style="width:480px;max-width:94vw"><q-card-section class="row items-center"><div><div class="text-h6">{{selected.nombre}}</div><div class="text-caption">Datos del proveedor</div></div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-list><q-item><q-item-section avatar><q-icon name="badge" color="primary"/></q-item-section><q-item-section><q-item-label>NIT</q-item-label><q-item-label caption>{{selected.nit||'No registrado'}}</q-item-label></q-item-section></q-item><q-item><q-item-section avatar><q-icon name="phone" color="primary"/></q-item-section><q-item-section><q-item-label>Teléfono</q-item-label><q-item-label caption>{{selected.telefono||'No registrado'}}</q-item-label></q-item-section></q-item><q-item><q-item-section avatar><q-icon name="location_on" color="primary"/></q-item-section><q-item-section><q-item-label>Dirección</q-item-label><q-item-label caption>{{selected.direccion||'No registrada'}}</q-item-label></q-item-section></q-item></q-list></q-card></q-dialog>
    <q-dialog v-model="editDialog"><q-card style="width:480px;max-width:94vw"><q-form @submit.prevent="saveEdit"><q-card-section class="row items-center"><div class="text-h6">Modificar proveedor</div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-card-section class="q-gutter-sm"><q-input v-model="form.nombre" autofocus dense outlined label="Nombre *"/><q-input v-model="form.nit" dense outlined label="NIT"/><q-input v-model="form.telefono" dense outlined label="Teléfono"/><q-input v-model="form.direccion" dense outlined label="Dirección"/></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" icon="save" label="Guardar cambios" type="submit" :loading="saving"/></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, getCurrentInstance, onMounted, reactive, ref } from 'vue'
const {proxy}=getCurrentInstance(),rows=ref([]),search=ref(''),loading=ref(false),dialog=ref(false),editDialog=ref(false),saving=ref(false),selected=ref({}),editingId=ref(null)
const form=reactive({nombre:'',nit:'',telefono:'',direccion:''})
const columns=[{name:'actions',label:'',align:'left'},{name:'nombre',label:'Proveedor',field:'nombre',align:'left'},{name:'nit',label:'NIT',field:'nit',align:'left'},{name:'datos',label:'Contacto',field:'telefono',align:'left'}]
const filtered=computed(()=>{const q=search.value?.toLowerCase().trim();return q?rows.value.filter(i=>[i.nombre,i.nit,i.telefono,i.direccion].some(v=>String(v||'').toLowerCase().includes(q))):rows.value})
function load(){loading.value=true;proxy.$axios.get('/proveedores').then(r=>rows.value=r.data).finally(()=>loading.value=false)}
function openEdit(row){editingId.value=row.id;Object.assign(form,{nombre:row.nombre,nit:row.nit||'',telefono:row.telefono||'',direccion:row.direccion||''});editDialog.value=true}
function saveEdit(){if(!form.nombre.trim())return proxy.$alert.error('Ingrese el nombre');saving.value=true;proxy.$axios.put(`/proveedores/${editingId.value}`,form).then(r=>{const index=rows.value.findIndex(i=>i.id===editingId.value);if(index>=0)rows.value[index]=r.data;editDialog.value=false;proxy.$alert.success('Proveedor modificado')}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo modificar')).finally(()=>saving.value=false)}
function removeProvider(row){proxy.$alert.dialog(`¿Eliminar al proveedor ${row.nombre}? Las compras anteriores conservarán su nombre.`).onOk(()=>proxy.$axios.delete(`/proveedores/${row.id}`).then(()=>{rows.value=rows.value.filter(i=>i.id!==row.id);proxy.$alert.success('Proveedor eliminado')}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo eliminar')))}
onMounted(load)
</script>
